language: php

php:
  - 7.1

# This triggers builds to run on the new TravisCI infrastructure.
# See: http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false

services:
  - mysql

## Cache composer
cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - cp .env.travis .env
  - mysql -e 'CREATE DATABASE test;'\
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-dist
  - php artisan migrate

script:
  # will add this shortly
  #- vendor/bin/phpcs --standard=psr2 src/
  # will add this a little less shortly
  #- vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover
  - vendor/bin/phpunit --no-coverage --stop-on-failure

after_script:
  - |
    if [[ "$TRAVIS_PHP_VERSION" != 'hhvm' && "$TRAVIS_PHP_VERSION" != '7.0' ]]; then
      wget https://scrutinizer-ci.com/ocular.phar
      php ocular.phar code-coverage:upload --format=php-clover coverage.clover
    fi

after_success:
  - curl -k X GET ${deploy}